services:
  - type: web
    name: oahsebackend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: oahse-backend-db
          property: connectionString

databases:
  - name: oahse-backend-db
    plan: free
    postgresVersion: 13
