# Generated by Django 5.1.1 on 2024-09-29 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='businessid',
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
    ]
